# Verbose level. 0 - errors, 1 - info, 2 - debug, 3 - trace
verbose = 1
# log_file = './log.log'

[server]
port = 12345
threads = 4

[mewe]
# Recomend use https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/ for Firefox
# extension and export cookies from incognito mode
cookies_path = "/path/to/mewe.com_cookies.txt"
limit = 10
pages = 1

[telegram]
# List of channels useful for opml export and override o
channels = [
    "oper_goblin",
    "dvachannel",
    # With config
    { slug = "foo_channel", pages = 2 },
    # Only slug
    { slug = "foo_channel" }
]
# For initial sync channel all records
pages = 1

# Add and/or override per channel config
[telegram.extra.channel_name]
# Num page for specific channel
pages = 5

# Maybe empty
[telegram.extra.channel_name_2]
[telegram.extra.channel_name_3]

[danbooru]
# limit = 50
# proxy = "https://host:port"
tags = [
    "masabodo",
    "touhou -guro" # touhou tag and not guro. Max 2 tags
]
