[workspace]
members = [
    "any2feed",
    "http_server",
    "feed",
    "mewe_api",
    "reqwest_mozilla_cookie",
    "test_utils",
    "telegram",
    "booru-rs",
]

#[patch.crates-io]
## This path for
#rustix = { git = "https://github.com/bytecodealliance/rustix/", branch = "v0.36.4" }
