[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.4.0" }
url = { version = "2.3.1" }
regex = { version = "1.7.1" }

log = "0.4.17"