name: CICD

env:
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"
  PROJECT_NAME: any2feed

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  version:
    name: check git version
    runs-on: ubuntu-20.04
    outputs:
      prerelease: ${{ !steps.version.outputs.is_stable }}
    steps:
      - name: Check version
        uses: apkawa/gh-action-semver-check@master
        id: version


  cargo_fmt:
    name: Ensure 'cargo fmt' has been run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: rustfmt
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check

  cargo_clippy:
    name: Ensure 'cargo clippy' has been run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: clippy
      - uses: actions/checkout@v3
      - run: cargo clippy

  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    needs:
      - version
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-apple-darwin         , os: macos-10.15 }
          #          - { target: x86_64-pc-windows-gnu       , os: windows-2019                  }
          - { target: x86_64-pc-windows-gnu       , os: ubuntu-20.04, use-cross: true, skip-test: true }
          - { target: x86_64-unknown-linux-gnu    , os: ubuntu-20.04,  }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install prerequisites for ubuntu
        shell: bash
        if: startsWith(matrix.job.os, 'ubuntu')
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libssl-dev pkg-config

      - name: Install prerequisites for macos
        shell: bash
        if: startsWith(matrix.job.os, 'macos')
        run: |
          brew install openssl

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal # minimal component installation (ie, no documentation)

      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        uses: actions-rs/cargo@v1
        with:

          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --locked --release --target=${{ matrix.job.target }} --bin any2feed

      - name: Strip debug information from executable
        id: strip
        shell: bash
        run: |
          # Figure out suffix of binary
          EXE_suffix=""
          case ${{ matrix.job.target }} in
            *-pc-windows-*) EXE_suffix=".exe" ;;
          esac;

          # Figure out what strip tool to use if any
          STRIP="strip"
          case ${{ matrix.job.target }} in
            arm-unknown-linux-*) STRIP="arm-linux-gnueabihf-strip" ;;
            aarch64-unknown-linux-gnu) STRIP="aarch64-linux-gnu-strip" ;;
            *-pc-windows-msvc) STRIP="" ;;
          esac;

          # Setup paths
          BIN_DIR="${{ env.CICD_INTERMEDIATES_DIR }}/stripped-release-bin/"
          mkdir -p "${BIN_DIR}"
          BIN_NAME="${{ env.PROJECT_NAME }}${EXE_suffix}"
          BIN_PATH="${BIN_DIR}/${{ matrix.job.target }}-${BIN_NAME}"

          # Copy the release build binary to the result location
          cp "target/${{ matrix.job.target }}/release/${BIN_NAME}" "${BIN_PATH}"
          # Also strip if possible
          if [ -n "${STRIP}" ]; then
            "${STRIP}" "${BIN_PATH}"
          fi
          # Let subsequent steps know where to find the (stripped) bin
          echo ::set-output name=BIN_PATH::${BIN_PATH}
          echo ::set-output name=BIN_NAME::${BIN_NAME}

      - name: Run tests
        uses: actions-rs/cargo@v1
        if: matrix.job.skip-test != true
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --locked --target=${{ matrix.job.target }}

      - name: "Artifact upload: "
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.job.target }}-${{ steps.strip.outputs.BIN_NAME }}
          path: ${{ steps.strip.outputs.BIN_PATH }}


      #      - name: Generate Changelog
      #        run: |
      #          cz ch --dry-run ${{ steps.version.outputs.full_with_prefix }}  > ${{ github.workspace }}-CHANGELOG.txt
      #          cat ${{ github.workspace }}-CHANGELOG.txt

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        if: ${{ !github.event.schedule && startsWith(github.ref, 'refs/tags') }}
        with:
          draft: true
          prerelease: ${{ needs.version.outputs.prerelease }}
          generate_release_notes: true
          files: |
            ${{ steps.strip.outputs.BIN_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
